fix PopUpInfo
mdn/web-components-examples pull request #46
Opened 2022-08-01 22:40 UTC by anhgelus

#### Summary
Fix the PopUp Info Custom Element's code.

#### Supporting details
With this bug, we cannot use `this.getAttributes()`.
So this code is not working.

We must use this method after the element's connection to the DOM.
This is why I put the part after the creation of the shadow root inside the `connectedCallback()` method.

#### Related content pull request
[The PR in the mdn/content](https://github.com/mdn/content/pull/19035)

2022-08-01 22:50 UTC, anhgelus commented
I just found 2 issues with this PR, this is the issue #34 and the issue #33

2022-08-02 05:55 UTC, teoli2003 requested changes

2022-08-02 05:55 UTC, teoli2003 commented on popup-info-box-web-component/main.js
> +    this.shadow.appendChild(style);
There is no `shadow` property on `this`, I think this should be `shadowRoot` that is defined on `Element`  and initialized via the `attachShadow()` method in the constructor.

2022-08-02 05:55 UTC, teoli2003 commented on popup-info-box-web-component/main.js
> +    this.shadow.appendChild(wrapper);
Ditto

2022-10-31 15:35 UTC, anhgelus commented
I just found the time to fix it.

2023-01-02 18:55 UTC, anhgelus commented
Just before merging it, I must update the file `index.html` of this example because it contains "defer".

2023-01-03 00:08 UTC, foobarbecue commented
I don't think we need this PR. `this.getAttributes()` works fine in the example -- there is no bug. If you modify the example to take out `defer`, then you create a bug.

2023-03-17 13:35 UTC, closed without merging