Update main.js
mdn/web-components-examples pull request #81
Opened 2024-11-08 17:22 UTC by Akiyamka

#### Summary
Unnecessary code removed.

- No need to declare the 'self' variable - we already have 'this' for this purpose
- No need to declare a constructor - JavaScript will call super automatically if no constructor is declared
- No need to convert the node list to an array - we have 'for' loops that can iterate over node lists directly

2025-03-28 14:43 UTC, bsmth commented
Thanks for the submission! @wbamberg you touched these last, do you want to have a quick look?

2025-12-18 22:18 UTC, pepelsbey requested changes
Thank you for the effort to improve the demo! I would only suggest keeping the code style intact (single/double quotes) and only leaving the meaningful changes. Basically, we use Prettier's default config. 

Also, there are many ways of doing the same thing in JS, and some of them improve in time, once we get new features or the browser support gets better. Others stay as a viable alternative and are just a matter of taste. I would suggest reviewing your suggestions from that perspective as well.

2025-12-19 09:32 UTC, Akiyamka commented
@pepelsbey Thank you for taking the time to review this merge request.  
I have formatted the file according to the Prettier default configuration.  
  
Regarding the other changes, you are absolutely right. Browser APIs as well as EcmaScript are improving over time, giving us the ability to write more expressive and understandable code, and the workarounds used in the past become redundant. Since people learning EcmaScript will also refer to these examples, I believe it would be appropriate to keep them up to date.

2026-01-13 10:36 UTC, pepelsbey approved these changes
Perfect! Thank you :)

2026-01-13 10:37 UTC, merged